name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.nodeversion }}"

    strategy:
      matrix:
        platform: [macos-13]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Fix Python conflicts between macOS runner and Homebrew
        run: |
          # see https://github.com/actions/setup-python/issues/577
          brew list -1 | grep python | while read formula; do brew unlink $formula; brew link --overwrite $formula; done

      - name: Install homebrew dependencies
        run: |
          set -x
          sudo chmod ugo+w /usr/local/bin
          brew install docker docker-compose lima

      - name: Install and start Colima
        run: |
          brew install colima
          colima version
          colima start --cpu 3 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run ci
        run: yarn ci

      - name: Turn off /clean up
        run: |
          colima stop

      - name: Clean up Homebrew
        continue-on-error: true
        run: |
          brew update
          brew autoremove
          brew cleanup