name: macos-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.platform }} ${{ matrix.nodeversion }}"

    strategy:
      matrix:
        platform: [macos-13]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
 
      - name: Install and start Colima (better Docker support for MacOS)
        run: |
          brew install docker docker-compose colima
          colima version
          colima start --cpu 3 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run ci
        run: yarn ci